remote_theme: pmarsceill/just-the-docs

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/icebreaker.png"
# Aux links for the upper right navigation
aux_links:
  "iCEBreaker on GitHub":
    - "//github.com/icebreaker-fpga"
# Footer content 
# appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2020 1BitSquared."
